---
title: "CHANGELOG"
output: html_document
---

Version=0.2.0
=============
1) Replace the variable "knots" by the variable "knot" everywhere to avoid confusion with knots() R build-in function
2) change notation paradigm:
variable "knot" refers to knots including ends (replace int_knots in version 1.0.1)
variable "ext_knot" refers to extended knot partition (replace knots in version 1.0.1)
3) Add case degree=0 which caused problems since some variables (coeff) lose 1 dimension. R automaticaly reduces the dimension of the arrays.
4) Add constrained regression by quartic splines using Karlin-studen technique for cubic polynomial (monotone) and quadratic polynomial (convex).
5) Add constrained regression by quadratic and linear splines. No major theoretical difficulty.
6) Unify all regression functions in a quantile_spline function with selection of the degree as a parameter
7) Render the spline container (list of knots, coefficients, degree) callable
8) Allow the call of a spline to pass the spline basis coefficient to accelerate the computations (as welle as in the function eval_spline) 

Version=0.1.0
=============
Initial version.
